import type { AdVideoAsset } from "./ad-video-assets";

const sourceRoot = "/assets/generated/ad-video/source-frames";
const rightsStatus = "original replacement required before commercial launch" as const;
const sharedNegativePrompt =
  "Avoid protected character likenesses, real console or game logos, legible third-party brand names, warped hands, unreadable UI labels, modern smartphones, glossy generic sci-fi, clean showroom lighting, and random extra characters.";

type ExtraAssetInput = Omit<
  AdVideoAsset,
  "src" | "sourceReference" | "width" | "height" | "negativePrompt" | "rightsStatus"
>;

const frame = (filename: string) => `${sourceRoot}/${filename}`;

const extraFrame = (asset: ExtraAssetInput): AdVideoAsset => ({
  ...asset,
  src: frame(asset.filename),
  sourceReference: `Image #${asset.imageNumber}, user-supplied AI reference, May 10 2026`,
  width: 1448,
  height: 1086,
  negativePrompt: sharedNegativePrompt,
  rightsStatus,
});

const shadowRights =
  "Contains a Shadow-like Sonic character, console/game marks, and brand-like UI. Use only as reference energy; replace with an original black-red Action Replay antihero mascot.";
const visorRights =
  "Contains Pokemon Colosseum/Wes/GameCube/Nintendo-style references and visor UI marks. Use only as reference; replace with an original Action Replay visor courier.";
const companionRights =
  "Contains Pokemon companion and Nintendo/GameCube references. Use only as reference; replace with an original shadow-fox companion and Action Replay universe props.";
const creatureRights =
  "Contains Mewtwo/Nintendo/GameCube references. Use only as reference; replace with an original pale psychic signal-creature.";
const arcadeRights =
  "Contains arcade cabinet/game brand cues, including Sega/Namco/DDRhythm-like references. Replace with original cabinet art and Action Replay signage.";
const carRights =
  "Contains tuner-car, racing-game, console, and garage brand cues. Use as composition and lighting reference only; rebuild with original Action Replay universe marks.";

export const extraAdVideoAssets: AdVideoAsset[] = [
  extraFrame({
    id: "ad-video-31-shadow-code-list-closeup",
    imageNumber: 31,
    filename: "31-shadow-code-list-closeup.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_28_18 PM.png",
    sha256: "775fadb7dec3b76d30a9e3ad69041fd9fd9b311e699739f4f3deba721c6c6cfb",
    assetCategory: "drop-card",
    sceneFamily: "code-sheet-ui",
    priority: "primary",
    usage: "Character-code insert for a hand-held cheat-sheet reveal before the world unlocks.",
    promptSummary: "Black-red antihero figure at a desk reading a printed Action Replay code list beside a CRT and game-room props.",
    alt: "Black and red game mascot figure reading a cheat-code sheet near a CRT.",
    visualRead: "Best close character-plus-code-sheet frame; the paper is clear enough to motivate a code-entry cut.",
    motionPrompt: "Slow push toward the paper as the character's hand steadies it, CRT glow rolls across the sheet, blue-red desk reflections flicker.",
    rightsNotes: shadowRights,
  }),
  extraFrame({
    id: "ad-video-32-shadow-ps2-codes-crt",
    imageNumber: 32,
    filename: "32-shadow-ps2-codes-crt.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_31_22 PM.png",
    sha256: "20baaae097d1e2e62ab0333334ec86ed668b17c93cd3065fb07bd1f65f738080",
    assetCategory: "drop-card",
    sceneFamily: "code-sheet-ui",
    priority: "support",
    usage: "Alternate code-sheet insert with stronger character face and CRT depth.",
    promptSummary: "Black-red antihero figure studying an Action Replay PS2-style code sheet on a dark desk.",
    alt: "Game mascot figure studies a printed cheat-code sheet beside a CRT.",
    visualRead: "Useful as a character reaction closeup after the file menu opens.",
    motionPrompt: "Rack focus from the code sheet to the character's eyes, desk light pulsing, CRT scanlines swimming in the background.",
    rightsNotes: shadowRights,
  }),
  extraFrame({
    id: "ad-video-33-tokyo-garage-woman-supra-menu",
    imageNumber: 33,
    filename: "33-tokyo-garage-woman-supra-menu.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_22_03 PM.png",
    sha256: "deac0245cf5e68598ef2384a408a923c97cfede0d564b66af1734b71f35920c7",
    assetCategory: "hero-poster",
    sceneFamily: "garage-racing",
    priority: "primary",
    usage: "Garage-world unlock shot with character, silver tuner car, and game menu overlay.",
    promptSummary: "Underground parking garage with silver tuner car, blue underglow, jacketed figure, and racing-menu HUD.",
    alt: "A silver tuner car glows blue in a wet underground garage beside a character.",
    visualRead: "Strong vehicle-world bridge from code UI into playable street culture.",
    motionPrompt: "Low slider move past the car nose, underglow reflecting on wet concrete, HUD menu blinking softly, character shifting weight.",
    rightsNotes: carRights,
  }),
  extraFrame({
    id: "ad-video-34-shadow-ps2-codes-crt-alt",
    imageNumber: 34,
    filename: "34-shadow-ps2-codes-crt-alt.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_31_22 PM.png",
    sha256: "20baaae097d1e2e62ab0333334ec86ed668b17c93cd3065fb07bd1f65f738080",
    assetCategory: "drop-card",
    sceneFamily: "code-sheet-ui",
    priority: "alternate",
    usage: "Exact duplicate archive of image 32, kept for source provenance.",
    promptSummary: "Duplicate of the antihero code-sheet desk closeup.",
    alt: "Duplicate code-sheet desk closeup with black and red game mascot figure.",
    visualRead: "Exact duplicate of image 32; use image 32 as the canonical version.",
    motionPrompt: "Use the motion direction from ad-video-32-shadow-ps2-codes-crt if this duplicate is selected.",
    rightsNotes: "Same rights risk as image 32.",
    duplicateOf: "ad-video-32-shadow-ps2-codes-crt",
  }),
  extraFrame({
    id: "ad-video-35-underground-garage-z-menu",
    imageNumber: 35,
    filename: "35-underground-garage-z-menu.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_23_49 PM.png",
    sha256: "d72537c0929b8828e8b1672b19949d69076a8ec37a2506ad9ac8ea9c326bf9cd",
    assetCategory: "hero-poster",
    sceneFamily: "garage-racing",
    priority: "support",
    usage: "Garage select-menu reference with two silver cars and wet concrete reflections.",
    promptSummary: "Underground garage, silver tuner cars, blue underglow, selection HUD, red signs, and rain-slick concrete.",
    alt: "Two silver tuner cars sit in a wet underground garage with a racing HUD.",
    visualRead: "Clean car-world option when a human character is not needed.",
    motionPrompt: "Slow pan across the cars, blue underglow shimmering, HUD selector ticking once, red garage signage reflecting in puddles.",
    rightsNotes: carRights,
  }),
  extraFrame({
    id: "ad-video-36-shadow-ar-max-code-sheet",
    imageNumber: 36,
    filename: "36-shadow-ar-max-code-sheet.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_28_27 PM.png",
    sha256: "9b63d863d566ff2dfaa7ca2d7fe1055ac4548f05e6e32195b64d61e14057fd19",
    assetCategory: "drop-card",
    sceneFamily: "code-sheet-ui",
    priority: "primary",
    usage: "Readable cheat-code sheet insert for the code-entry beat.",
    promptSummary: "Black-red antihero figure holding a printed Action Replay code sheet under CRT light.",
    alt: "A character holds an Action Replay code sheet in a dark gaming room.",
    visualRead: "Best paper-in-hand composition; it makes the cheat-code mechanic tactile.",
    motionPrompt: "Macro handheld push over the code sheet, fingertips flexing, paper texture visible, CRT blue wash and red practical lights breathing.",
    rightsNotes: shadowRights,
  }),
  extraFrame({
    id: "ad-video-37-garage-two-silver-cars-hud",
    imageNumber: 37,
    filename: "37-garage-two-silver-cars-hud.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_23_54 PM.png",
    sha256: "8b2436569683abee6ad8f558d0f96b2e058e541828db507ceaacca5975b7c37c",
    assetCategory: "hero-poster",
    sceneFamily: "garage-racing",
    priority: "support",
    usage: "Wide garage racing-world reference with two cars and blue-lit floor.",
    promptSummary: "Underground garage with two silver cars, blue neon underglow, wet reflective floor, and game HUD overlays.",
    alt: "Two blue-lit cars are parked in a dark wet garage with game HUD text.",
    visualRead: "Useful for an interstitial car-world cut that avoids character likeness issues.",
    motionPrompt: "Dolly between the two cars, tire reflections stretching across wet floor, menu text flickering as if the garage loaded from a save file.",
    rightsNotes: carRights,
  }),
  extraFrame({
    id: "ad-video-38-wes-action-replay-visor-closeup",
    imageNumber: 38,
    filename: "38-wes-action-replay-visor-closeup.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_50_56 PM.png",
    sha256: "4ce92ca1d2fcc8bc3f54234a296b19b0cf9de1a42215cb137f5069f1099b9925",
    assetCategory: "ui-badge",
    sceneFamily: "visor-courier",
    priority: "primary",
    usage: "Visor-courier hero closeup for the Action Replay unlock protagonist.",
    promptSummary: "White-haired blue-jacket courier with mirrored Action Replay visor and GameCube-era UI reflections.",
    alt: "A white-haired courier wears a mirrored blue Action Replay visor.",
    visualRead: "Strongest face/visor frame and a good character identity anchor.",
    motionPrompt: "Slow push into the visor reflection, blue code text crawling across glass, tiny head turn, cold rim light skating over the jacket.",
    rightsNotes: visorRights,
  }),
  extraFrame({
    id: "ad-video-39-shadow-on-car-hood-press-start",
    imageNumber: 39,
    filename: "39-shadow-on-car-hood-press-start.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_29_49 PM.png",
    sha256: "45cd520bc1407891b43b75fef8a9230fe678ae08fe57d7bc39f69c0fce1cccf6",
    assetCategory: "hero-poster",
    sceneFamily: "shadow-garage",
    priority: "primary",
    usage: "Antihero-on-car poster shot for the press-start moment.",
    promptSummary: "Black-red antihero mascot sitting on a silver tuner car hood in a blue garage with Action Replay UI.",
    alt: "A black-red game mascot sits on a blue-lit silver car hood.",
    visualRead: "Best character-plus-car title-card energy in the Shadow-style batch.",
    motionPrompt: "Locked poster frame, headlights breathing, garage mist drifting, UI start prompt blinking, character silhouette subtly rocking.",
    rightsNotes: shadowRights,
  }),
  extraFrame({
    id: "ad-video-40-wes-code-engine-visor-closeup",
    imageNumber: 40,
    filename: "40-wes-code-engine-visor-closeup.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_43_21 PM.png",
    sha256: "0912cd394cc45dc7ef6e196ea14ac1f7212b23e4136191b6e831981bdd61b4d6",
    assetCategory: "ui-badge",
    sceneFamily: "visor-courier",
    priority: "primary",
    usage: "Code-engine visor insert for showing the unlock happening on the character's face.",
    promptSummary: "White-haired visor courier closeup with dense blue code reflected across the glasses.",
    alt: "Blue code text reflects across a courier's mirrored visor.",
    visualRead: "Cleanest visor-code read; useful as a UI transition from paper codes to character.",
    motionPrompt: "Extreme slow zoom, code lines scrolling across the visor, eyelids barely moving, blue reflections pulsing in sync with a boot sound.",
    rightsNotes: visorRights,
  }),
  extraFrame({
    id: "ad-video-41-shadow-loading-car-hood-poster",
    imageNumber: 41,
    filename: "41-shadow-loading-car-hood-poster.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_26_58 PM.png",
    sha256: "d697807abed372f28db48455d383963849631c86fc30f4979584270e3ddc25be",
    assetCategory: "hero-poster",
    sceneFamily: "shadow-garage",
    priority: "primary",
    usage: "Loading-screen style character/car poster for the garage chapter.",
    promptSummary: "Antihero mascot sitting on a car hood under blue garage lights, with poster UI and loading text.",
    alt: "A black-red mascot sits on a silver car hood in a loading-screen style poster.",
    visualRead: "Best polished poster composition in the garage set.",
    motionPrompt: "Subtle zoom as loading UI ticks upward, fluorescent lights buzz, reflections move across the hood, character shoes catching blue highlights.",
    rightsNotes: shadowRights,
  }),
  extraFrame({
    id: "ad-video-42-shadow-smoking-car-hood",
    imageNumber: 42,
    filename: "42-shadow-smoking-car-hood.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_31_02 PM.png",
    sha256: "8662938dc7bbd30b9082bf2876a42357676c90d39b96031a5778721df25e31be",
    assetCategory: "hero-poster",
    sceneFamily: "shadow-garage",
    priority: "support",
    usage: "Cool-down garage beat with character seated on a hood near vending light.",
    promptSummary: "Black-red antihero mascot on a silver car hood in a wet blue garage, smoking pose, vending glow behind.",
    alt: "A black-red mascot sits on a car hood in a blue underground garage.",
    visualRead: "Good mood frame, less UI-specific than image 41.",
    motionPrompt: "Smoke curls upward, neon reflections ripple on the hood, camera drifts sideways, red vending light pulses behind the character.",
    rightsNotes: shadowRights,
  }),
  extraFrame({
    id: "ad-video-43-shadow-vending-poster-layout",
    imageNumber: 43,
    filename: "43-shadow-vending-poster-layout.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_32_28 PM.png",
    sha256: "aa371033d9084773a0017433a15211173f03064bc0d727e966499729bb47190d",
    assetCategory: "shop-banner",
    sceneFamily: "retail-exterior",
    priority: "support",
    usage: "Vending-machine poster composition for a street retail cutaway.",
    promptSummary: "Antihero mascot standing beside a glowing vending machine in a blue urban alley poster layout.",
    alt: "A black-red mascot stands beside a vending machine in a dark blue alley.",
    visualRead: "Useful bridge from garage to street retail, but needs a brand-safe character rebuild.",
    motionPrompt: "Slow vertical tilt from wet ground to vending light, poster typography flickering, character shadow stretching against the wall.",
    rightsNotes: shadowRights,
  }),
  extraFrame({
    id: "ad-video-44-shadow-gp-car-hood-poster",
    imageNumber: 44,
    filename: "44-shadow-gp-car-hood-poster.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_28_53 PM.png",
    sha256: "7c183ab1b054600d43d22ee607adb08a86a069bd305ce91b4938781fb5dc660f",
    assetCategory: "hero-poster",
    sceneFamily: "shadow-garage",
    priority: "primary",
    usage: "Garage-poster hero with mascot on car hood and Action Replay mark placement.",
    promptSummary: "Black-red antihero mascot on a silver car hood with blue underglow and game-poster framing.",
    alt: "A black-red mascot sits on a silver car hood in a game-poster layout.",
    visualRead: "Strong clean hero frame, close to a final poster if rebuilt with original character art.",
    motionPrompt: "Poster-like slow parallax, car hood highlights crawling, garage light flicker, Action Replay-style corner bug gently glowing.",
    rightsNotes: shadowRights,
  }),
  extraFrame({
    id: "ad-video-45-shadow-enters-fisheye-arcade",
    imageNumber: 45,
    filename: "45-shadow-enters-fisheye-arcade.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_33_19 PM.png",
    sha256: "a683c42e75c4e17ce5870a3bedae8d1568235d45826a038bd33d44c420867e3c",
    assetCategory: "hero-poster",
    sceneFamily: "arcade-interior",
    priority: "primary",
    usage: "Arcade-entry shot for the expanded game-world chapter.",
    promptSummary: "Fisheye arcade hallway with black-red mascot walking past cabinets under glossy blue-purple lights.",
    alt: "A black-red mascot walks through a fisheye arcade hallway.",
    visualRead: "Best kinetic arcade transition in the Shadow-style set.",
    motionPrompt: "Fisheye follow-cam from behind, cabinet lights streaking, floor reflections sliding, VHS timestamp jittering as the character walks forward.",
    rightsNotes: arcadeRights,
  }),
  extraFrame({
    id: "ad-video-46-shadow-pause-car-hood",
    imageNumber: 46,
    filename: "46-shadow-pause-car-hood.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_28_34 PM.png",
    sha256: "15e0cafb1013b4e5a63b064d328238eeb14848956c4d5e88e1b5a90f568845b2",
    assetCategory: "hero-poster",
    sceneFamily: "shadow-garage",
    priority: "support",
    usage: "Paused-game variation of the character-on-car garage poster.",
    promptSummary: "Antihero mascot seated on a silver car hood with pause/menu UI over a blue underground garage.",
    alt: "A mascot sits on a car hood under a paused-game menu overlay.",
    visualRead: "Useful if the edit needs an obvious pause/override gag.",
    motionPrompt: "Menu overlay blinks while the garage moves underneath it, headlights pulse once, character remains mostly still like a paused game.",
    rightsNotes: shadowRights,
  }),
  extraFrame({
    id: "ad-video-47-shadow-gp-car-hood-poster-alt",
    imageNumber: 47,
    filename: "47-shadow-gp-car-hood-poster-alt.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_28_53 PM.png",
    sha256: "7c183ab1b054600d43d22ee607adb08a86a069bd305ce91b4938781fb5dc660f",
    assetCategory: "hero-poster",
    sceneFamily: "shadow-garage",
    priority: "alternate",
    usage: "Exact duplicate archive of image 44, kept for source provenance.",
    promptSummary: "Duplicate of the mascot-on-car garage poster.",
    alt: "Duplicate garage poster with mascot seated on a car hood.",
    visualRead: "Exact duplicate of image 44; use image 44 as the canonical version.",
    motionPrompt: "Use the motion direction from ad-video-44-shadow-gp-car-hood-poster if this duplicate is selected.",
    rightsNotes: "Same rights risk as image 44.",
    duplicateOf: "ad-video-44-shadow-gp-car-hood-poster",
  }),
  extraFrame({
    id: "ad-video-48-wes-sys-menu-visor-closeup",
    imageNumber: 48,
    filename: "48-wes-sys-menu-visor-closeup.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_45_53 PM.png",
    sha256: "098d629f5ea85fcc4153ee0818fefdc39320c60f087e4c438501a861ed6fb1f0",
    assetCategory: "ui-badge",
    sceneFamily: "visor-courier",
    priority: "support",
    usage: "System-menu visor closeup for loading-device UI shots.",
    promptSummary: "White-haired visor courier closeup with blue system menu reflected across mirrored lenses.",
    alt: "A white-haired courier's visor reflects a blue system menu.",
    visualRead: "Good close insert for device booting, slightly less clean than image 40.",
    motionPrompt: "Tiny camera creep, menu rows scrolling in the visor reflection, cold blue light moving across the cheeks.",
    rightsNotes: visorRights,
  }),
  extraFrame({
    id: "ad-video-49-wes-device-info-visor-closeup",
    imageNumber: 49,
    filename: "49-wes-device-info-visor-closeup.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_48_32 PM.png",
    sha256: "d871a9e52b64e5ace80a0d0f4f02ce23cddf8f74759413c2f6bcdd8b34331f63",
    assetCategory: "ui-badge",
    sceneFamily: "visor-courier",
    priority: "support",
    usage: "Device-info visor insert with compact blue diagnostic text.",
    promptSummary: "White-haired visor courier closeup with blue device information reflected in visor glass.",
    alt: "Blue device information text reflects across a courier's visor.",
    visualRead: "Best for a diagnostic/device-info micro cut.",
    motionPrompt: "Code columns crawl from right to left across the visor, face held still, background light breathing softly.",
    rightsNotes: visorRights,
  }),
  extraFrame({
    id: "ad-video-50-wes-chainlink-pokeball-alley",
    imageNumber: 50,
    filename: "50-wes-chainlink-pokeball-alley.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_39_40 PM.png",
    sha256: "af574e44b100359ae2f4fa05077d09033aefd0278c47c68b35baf2056b8e8b6c",
    assetCategory: "hero-poster",
    sceneFamily: "creature-companion-city",
    priority: "support",
    usage: "Chainlink-alley courier frame with handheld creature-capture prop energy.",
    promptSummary: "Blue-jacket visor courier in a rainy alley holding a round capture-device prop near chainlink fencing.",
    alt: "A visor courier stands by chainlink fencing in a rainy neon alley.",
    visualRead: "Good gritty alley texture, but the handheld prop needs a full original redesign.",
    motionPrompt: "Low alley drift past the fence, rain glints on the device, visor glow intensifies, city light streaks behind the character.",
    rightsNotes: companionRights,
  }),
  extraFrame({
    id: "ad-video-51-shadow-arcade-hallway-over-shoulder",
    imageNumber: 51,
    filename: "51-shadow-arcade-hallway-over-shoulder.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_34_06 PM.png",
    sha256: "8fa01cdf072b3fc2d2d376d2375fcc58ee3956f15bf0531de69b12070cccf603",
    assetCategory: "hero-poster",
    sceneFamily: "arcade-interior",
    priority: "primary",
    usage: "Over-shoulder arcade hall shot with strong depth and cabinet glow.",
    promptSummary: "Black-red antihero mascot seen from behind walking down a glossy arcade hallway.",
    alt: "A black-red mascot walks away through a neon-lit arcade hall.",
    visualRead: "Best over-shoulder arcade depth frame, useful for a game-world travel beat.",
    motionPrompt: "Follow behind the character, fisheye cabinet lights warping at frame edges, floor reflections rippling with each step.",
    rightsNotes: arcadeRights,
  }),
  extraFrame({
    id: "ad-video-52-wes-ramen-ds-rain-window",
    imageNumber: 52,
    filename: "52-wes-ramen-ds-rain-window.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_41_22 PM.png",
    sha256: "40686e78fcfb21dce7894daabf16c8a1352c89049cc6528b412771172632e7f4",
    assetCategory: "hero-poster",
    sceneFamily: "creature-companion-city",
    priority: "support",
    usage: "Quiet ramen-booth character beat before the city unlock escalates.",
    promptSummary: "White-haired visor courier sitting at a ramen counter with handheld game device, rain and neon outside.",
    alt: "A visor courier sits at a ramen counter with a handheld device beside a rainy window.",
    visualRead: "Strong human downtime shot with real street texture.",
    motionPrompt: "Window rain runs downward, handheld screen glow flickers on the face, ramen steam drifts, city reflections pulse outside.",
    rightsNotes: companionRights,
  }),
  extraFrame({
    id: "ad-video-53-wes-umbreon-neon-alley",
    imageNumber: 53,
    filename: "53-wes-umbreon-neon-alley.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_37_15 PM.png",
    sha256: "85b5b17f5436c9f11df7cc28a4acdd8b21edc9b34ea570dc3e3fd441da51a64a",
    assetCategory: "hero-poster",
    sceneFamily: "creature-companion-city",
    priority: "primary",
    usage: "Courier and shadow-companion alley hero shot.",
    promptSummary: "Blue-jacket visor courier in rainy neon alley with a dark fox-like companion and red-blue signage.",
    alt: "A visor courier stands in a rainy alley with a dark fox-like companion.",
    visualRead: "Best companion-world image, high brand-ad potential after original character redesign.",
    motionPrompt: "Slow forward walk, companion eyes glowing, rain mist swirling at ankle height, visor and alley signs reflecting in puddles.",
    rightsNotes: companionRights,
  }),
  extraFrame({
    id: "ad-video-54-wes-action-replay-visor-logo-closeup",
    imageNumber: 54,
    filename: "54-wes-action-replay-visor-logo-closeup.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_49_55 PM.png",
    sha256: "6257a50e96eb18d8bc67cecd835d29f04037122110251112feeea018be735276",
    assetCategory: "ui-badge",
    sceneFamily: "visor-courier",
    priority: "primary",
    usage: "Action Replay logo reflection closeup for a clean brand-recognition cut.",
    promptSummary: "White-haired courier with mirrored visor reflecting an Action Replay logo in cold blue light.",
    alt: "Action Replay lettering reflects across a courier's mirrored visor.",
    visualRead: "Cleanest brand reflection closeup in the visor batch.",
    motionPrompt: "Logo reflection sharpens then glitches, camera inches closer, blue light flares across the visor edge.",
    rightsNotes: visorRights,
  }),
  extraFrame({
    id: "ad-video-55-shadow-vending-game-hud",
    imageNumber: 55,
    filename: "55-shadow-vending-game-hud.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_33_29 PM.png",
    sha256: "dc2ec94cdbcd9962426a23c7057a2f4e9a3d1051ccb8389201b61f7f8f6a691b",
    assetCategory: "shop-banner",
    sceneFamily: "retail-exterior",
    priority: "support",
    usage: "Vending-machine street cut with game HUD and antihero figure.",
    promptSummary: "Black-red mascot outside glowing vending machines with game HUD overlay and dark city backdrop.",
    alt: "A black-red mascot stands beside vending machines under a game HUD overlay.",
    visualRead: "Good street-retail texture, strongest when paired with storefront shots 27 and 29.",
    motionPrompt: "Vending lights flicker, HUD minimap pulses, rain speckles the lens, character turns slightly toward the machine.",
    rightsNotes: shadowRights,
  }),
  extraFrame({
    id: "ad-video-56-shadow-red-vending-rooftop",
    imageNumber: 56,
    filename: "56-shadow-red-vending-rooftop.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_32_35 PM.png",
    sha256: "1991d14e243984ebe7ca6f2025d205b9f766ab79a4eb1d6778f211e2b318cc44",
    assetCategory: "hero-poster",
    sceneFamily: "retail-exterior",
    priority: "support",
    usage: "Red vending-alley silhouette shot for a darker street beat.",
    promptSummary: "Black-red antihero mascot leaning near a glowing red vending sign on a rainy rooftop alley edge.",
    alt: "A black-red mascot stands near a red vending sign in a dark rainy city.",
    visualRead: "Moody silhouette frame with strong red negative space.",
    motionPrompt: "Rain falls through red signage, character silhouette breathes, distant skyline lights twinkle, camera tilts up slowly.",
    rightsNotes: shadowRights,
  }),
  extraFrame({
    id: "ad-video-57-shadow-cheat-code-sheet-closeup",
    imageNumber: 57,
    filename: "57-shadow-cheat-code-sheet-closeup.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_29_27 PM.png",
    sha256: "0f8e1e9b29c2150b706deb72cad58be86dccfe5538c3b97aa525b3c4cd1240f8",
    assetCategory: "drop-card",
    sceneFamily: "code-sheet-ui",
    priority: "primary",
    usage: "Extreme cheat-code sheet closeup for a code-entry insert.",
    promptSummary: "Close view of a gloved hand pointing at an Action Replay cheat-code sheet with CRT glow and dark desk props.",
    alt: "A gloved hand points at a printed Action Replay cheat-code sheet.",
    visualRead: "Most readable code-paper insert in the character batch.",
    motionPrompt: "Finger traces down the list, paper grain sharp, blue scanline reflections sliding over the page, tiny handheld shake.",
    rightsNotes: shadowRights,
  }),
  extraFrame({
    id: "ad-video-58-wes-rooftop-fence-colosseum-promo",
    imageNumber: 58,
    filename: "58-wes-rooftop-fence-colosseum-promo.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_38_33 PM.png",
    sha256: "0a5a1269d38c6ba6521376de44c7db18afec95660d2b7bcda7c3ce31e238d86d",
    assetCategory: "hero-poster",
    sceneFamily: "creature-companion-city",
    priority: "support",
    usage: "Rooftop fence courier hero with handheld companion-world promotion energy.",
    promptSummary: "Blue-jacket visor courier by chainlink rooftop fence, city lights, handheld capture prop, and promo-style corner marks.",
    alt: "A visor courier stands by a rooftop chainlink fence under blue night light.",
    visualRead: "Good low-angle promo frame, but overt legacy-game marks need replacement.",
    motionPrompt: "Rooftop wind moves coat edges, fence foreground parallax slides, city lights blink, handheld prop glows once.",
    rightsNotes: companionRights,
  }),
  extraFrame({
    id: "ad-video-59-wes-menu-visor-closeup",
    imageNumber: 59,
    filename: "59-wes-menu-visor-closeup.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_42_29 PM.png",
    sha256: "6cba94becedce4b6274692ceb95dcfb94bf21e2ff0d27451009844b260c61520",
    assetCategory: "ui-badge",
    sceneFamily: "visor-courier",
    priority: "support",
    usage: "Menu visor reflection cut for the courier UI sequence.",
    promptSummary: "White-haired visor courier closeup with a reflected game menu and blue interface text.",
    alt: "A visor courier's mirrored glasses show a blue game menu.",
    visualRead: "Solid UI reflection alternate with more face shadow than image 40.",
    motionPrompt: "Menu rows blink over the visor, camera holds close, reflected light pulses in a cold rhythm.",
    rightsNotes: visorRights,
  }),
  extraFrame({
    id: "ad-video-60-psychic-creature-rooftop-sp-day",
    imageNumber: 60,
    filename: "60-psychic-creature-rooftop-sp-day.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_47_11 PM.png",
    sha256: "83f89f1b5fd0f66139a8662426d5ae6db7d0f7e684529c594f59145cfceb5ed1",
    assetCategory: "hero-poster",
    sceneFamily: "rooftop-creature",
    priority: "primary",
    usage: "Psychic signal-creature rooftop shot with handheld device silhouette.",
    promptSummary: "Pale psychic creature on a rooftop holding a clamshell handheld device, city skyline and console-era UI marks.",
    alt: "A pale psychic creature holds a handheld device on a rooftop.",
    visualRead: "Best daytime/sunset creature silhouette for a surreal unlock beat.",
    motionPrompt: "Slow orbit around the creature, handheld screen glow rising, skyline haze moving, tail silhouette framing the city.",
    rightsNotes: creatureRights,
  }),
  extraFrame({
    id: "ad-video-61-wes-restaurant-gameboy-sp",
    imageNumber: 61,
    filename: "61-wes-restaurant-gameboy-sp.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_41_13 PM.png",
    sha256: "bd2cdf62c23dad6210b63211d8f31b36ac5ef8e7925e22980d96ffea40839805",
    assetCategory: "hero-poster",
    sceneFamily: "creature-companion-city",
    priority: "support",
    usage: "Restaurant booth handheld-game insert for quiet character pacing.",
    promptSummary: "White-haired visor courier at a restaurant booth using a clamshell handheld device with ramen and rainy window light.",
    alt: "A visor courier uses a clamshell handheld at a restaurant booth.",
    visualRead: "Good intimate handheld-device story beat.",
    motionPrompt: "Camera pushes across ramen bowl to handheld screen, steam lifts, neon rain outside refracts through the window.",
    rightsNotes: companionRights,
  }),
  extraFrame({
    id: "ad-video-62-wes-umbreon-action-replay-alley",
    imageNumber: 62,
    filename: "62-wes-umbreon-action-replay-alley.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_33_48 PM.png",
    sha256: "cc84a144d13c63241b1df8038881d1591ceb77c0a4b5a8755e826a8f728b331c",
    assetCategory: "hero-poster",
    sceneFamily: "creature-companion-city",
    priority: "primary",
    usage: "Courier and companion walking shot with Action Replay corner branding.",
    promptSummary: "Blue-jacket visor courier and dark fox-like companion walking through a rainy neon alley.",
    alt: "A visor courier and dark fox companion walk through a neon alley.",
    visualRead: "Strong moving-character frame for the companion-world chapter.",
    motionPrompt: "Track backward as courier and companion advance, puddles splashing subtly, visor light and companion rings glowing through rain.",
    rightsNotes: companionRights,
  }),
  extraFrame({
    id: "ad-video-63-wes-umbreon-unlock-alley",
    imageNumber: 63,
    filename: "63-wes-umbreon-unlock-alley.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_36_05 PM.png",
    sha256: "0ffcddfb1d7ecb967d83cb75b5a1139eaf57b08e062c56adc337b0c2762cc84f",
    assetCategory: "hero-poster",
    sceneFamily: "creature-companion-city",
    priority: "primary",
    usage: "Main companion unlock hero shot for the expanded ad bank.",
    promptSummary: "Visor courier and dark fox-like companion standing in a rainy alley with blue-red signage and Action Replay UI.",
    alt: "A visor courier stands with a dark fox companion in a rainy blue-red alley.",
    visualRead: "Best combined character, companion, and brand-world frame.",
    motionPrompt: "Slow heroic push-in, companion eyes glow, jacket catches rain, UI corner marks pulse like an unlocked status screen.",
    rightsNotes: companionRights,
  }),
  extraFrame({
    id: "ad-video-64-wes-umbreon-ui-border-alley",
    imageNumber: 64,
    filename: "64-wes-umbreon-ui-border-alley.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_35_59 PM.png",
    sha256: "c8ba367d283172818195572a99fcba4d137ca99d3c62e0f9a02aa2d2e041a561",
    assetCategory: "hero-poster",
    sceneFamily: "creature-companion-city",
    priority: "support",
    usage: "UI-bordered alley alternate for companion-world packaging.",
    promptSummary: "Blue-jacket visor courier with dark fox-like companion in an alley framed by game UI borders.",
    alt: "A visor courier and dark fox companion stand in an alley inside a blue UI frame.",
    visualRead: "Useful for a more overt game-screen treatment.",
    motionPrompt: "UI frame jitters and locks on, alley rain continues behind it, companion shifts one step into the light.",
    rightsNotes: companionRights,
  }),
  extraFrame({
    id: "ad-video-65-shadow-fisheye-arcade-ddr",
    imageNumber: 65,
    filename: "65-shadow-fisheye-arcade-ddr.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_35_24 PM.png",
    sha256: "542edaea1044733e297dd45dc8322ce90aea88596d60812c66ff9dd248c2f26d",
    assetCategory: "hero-poster",
    sceneFamily: "arcade-interior",
    priority: "primary",
    usage: "Fisheye arcade dance-machine shot for high-energy mid-ad motion.",
    promptSummary: "Black-red antihero mascot running through a neon arcade with dance cabinets and glossy reflective floor.",
    alt: "A black-red mascot runs through a neon arcade with fisheye lens distortion.",
    visualRead: "Most kinetic arcade frame; good for quick high-energy motion.",
    motionPrompt: "Fast fisheye follow shot, cabinet lights streaking, floor reflections smearing, character feet hitting glossy tiles in rhythm.",
    rightsNotes: arcadeRights,
  }),
  extraFrame({
    id: "ad-video-66-shadow-fisheye-arcade-walk",
    imageNumber: 66,
    filename: "66-shadow-fisheye-arcade-walk.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_34_44 PM.png",
    sha256: "ccddedc8a19c5648d85c95e81c130ca7a25d0bb76fafbc1efcab60cce07902c4",
    assetCategory: "hero-poster",
    sceneFamily: "arcade-interior",
    priority: "primary",
    usage: "Symmetrical arcade walk shot with deep cabinet rows.",
    promptSummary: "Black-red antihero mascot walking down a symmetrical neon arcade corridor.",
    alt: "A black-red mascot walks down a symmetrical arcade corridor.",
    visualRead: "Best centered arcade corridor frame for a clean transition.",
    motionPrompt: "Centered steadicam push behind the character, cabinet rows flashing in sequence, wet-looking floor stretching reflections toward camera.",
    rightsNotes: arcadeRights,
  }),
  extraFrame({
    id: "ad-video-67-wes-restaurant-booth-ds-rain",
    imageNumber: 67,
    filename: "67-wes-restaurant-booth-ds-rain.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_41_33 PM.png",
    sha256: "5cebbcd4c152b2e775a626be5e1cd47c19f022594f4d9301f537a6cc1dfcb10c",
    assetCategory: "hero-poster",
    sceneFamily: "creature-companion-city",
    priority: "support",
    usage: "Alternate restaurant booth shot with wider neon window context.",
    promptSummary: "Visor courier at a red restaurant booth with handheld device, ramen bowl, and rainy neon street outside.",
    alt: "A visor courier sits at a red booth with ramen and a handheld device.",
    visualRead: "Good atmospheric alternate to image 52 with more booth color.",
    motionPrompt: "Sideways booth slide, rain-streaked window parallax, handheld screen glow reflecting on the table.",
    rightsNotes: companionRights,
  }),
  extraFrame({
    id: "ad-video-68-shadow-record-arcade-walk",
    imageNumber: 68,
    filename: "68-shadow-record-arcade-walk.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_33_14 PM.png",
    sha256: "fe6837c65cb97af956ab61b0e3f86635610cd4e35252b9a6839d9c6cfb3918ef",
    assetCategory: "hero-poster",
    sceneFamily: "arcade-interior",
    priority: "support",
    usage: "Record-mode arcade walking shot with timestamp overlays.",
    promptSummary: "Black-red antihero mascot walking through neon arcade rows with camcorder record UI.",
    alt: "A camcorder-style recording of a mascot walking through a neon arcade.",
    visualRead: "Good VHS/camcorder texture for a found-footage edit.",
    motionPrompt: "Handheld record-mode walk, timestamp jitter, arcade lights flaring, slight lens smear on bright cabinet edges.",
    rightsNotes: arcadeRights,
  }),
  extraFrame({
    id: "ad-video-69-wes-fence-low-angle-colosseum",
    imageNumber: 69,
    filename: "69-wes-fence-low-angle-colosseum.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_40_26 PM.png",
    sha256: "94bb83bb11e9254accb7090cf1628a9c61ebad1215fcc471d8cec1293c6e0d6d",
    assetCategory: "hero-poster",
    sceneFamily: "creature-companion-city",
    priority: "support",
    usage: "Low-angle fence hero for the courier character bank.",
    promptSummary: "Blue-jacket visor courier leaning at chainlink fence in a wet blue city night scene.",
    alt: "A visor courier leans against a chainlink fence in a rainy city.",
    visualRead: "Strong low-angle swagger frame, best used as a still poster reference.",
    motionPrompt: "Camera rises along the fence, jacket edges fluttering, city bokeh and visor glow pulsing behind rain.",
    rightsNotes: companionRights,
  }),
  extraFrame({
    id: "ad-video-70-psychic-creature-rooftop-sp-sunset",
    imageNumber: 70,
    filename: "70-psychic-creature-rooftop-sp-sunset.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_50_45 PM.png",
    sha256: "d0fb34ab02dbd0c66e716ec5d3460eebc9a29c8a1f4c4955d58e659a420573a5",
    assetCategory: "hero-poster",
    sceneFamily: "rooftop-creature",
    priority: "primary",
    usage: "Sunset rooftop creature shot for the surreal unlock chapter.",
    promptSummary: "Pale psychic creature on rainy rooftop with city skyline and handheld device, moody dusk lighting.",
    alt: "A pale psychic creature holds a handheld device on a rainy rooftop at dusk.",
    visualRead: "Best skyline/creature mood shot, with cleaner negative space than image 60.",
    motionPrompt: "Slow crane around the creature, handheld glow intensifies, skyline lights flicker on, rain ripples across rooftop puddles.",
    rightsNotes: creatureRights,
  }),
  extraFrame({
    id: "ad-video-71-wes-gamecube-visor-closeup",
    imageNumber: 71,
    filename: "71-wes-gamecube-visor-closeup.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_42_12 PM.png",
    sha256: "968d81df837b8fab21be5c65a3fbe0fc12c7e42b658fc16d95a8bb6384ba3184",
    assetCategory: "ui-badge",
    sceneFamily: "visor-courier",
    priority: "support",
    usage: "Console-logo visor closeup reference for device-era UI glow.",
    promptSummary: "White-haired visor courier closeup with cube-console branding and blue reflected interface.",
    alt: "A visor courier's glasses reflect blue console-era interface text.",
    visualRead: "Useful only after replacing the console-logo language with original AR glyphs.",
    motionPrompt: "Logo reflection dissolves into Action Replay glyphs, visor glass catches a blue light sweep, face remains statue-still.",
    rightsNotes: visorRights,
  }),
  extraFrame({
    id: "ad-video-72-shadow-fisheye-sega-rally-arcade",
    imageNumber: 72,
    filename: "72-shadow-fisheye-sega-rally-arcade.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_33_59 PM.png",
    sha256: "916b7eb4df223d685875e1a816e57cd7f901f16020c5795d11de472c894a4537",
    assetCategory: "hero-poster",
    sceneFamily: "arcade-interior",
    priority: "support",
    usage: "Racing-arcade fisheye reference for cabinet-row motion.",
    promptSummary: "Black-red antihero mascot moving through a fisheye racing arcade with bright cabinet rows.",
    alt: "A black-red mascot walks through a racing arcade under fisheye distortion.",
    visualRead: "Good racing arcade texture but highest cabinet-brand replacement need.",
    motionPrompt: "Fisheye glide past racing cabinets, reflections stretching, cabinet lights pulsing as if cheat codes are activating each machine.",
    rightsNotes: arcadeRights,
  }),
  extraFrame({
    id: "ad-video-73-shadow-fisheye-arcade-cabinets",
    imageNumber: 73,
    filename: "73-shadow-fisheye-arcade-cabinets.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_35_07 PM.png",
    sha256: "98eca25472860223bf0af0ae7b445402ce2f026bd74915bcf60c3df79d53d3ff",
    assetCategory: "hero-poster",
    sceneFamily: "arcade-interior",
    priority: "support",
    usage: "Dense cabinet-row arcade alternate for texture and light.",
    promptSummary: "Black-red antihero mascot centered in a dense arcade aisle with glowing blue cabinet rows.",
    alt: "A black-red mascot stands in a dense arcade aisle with glowing cabinets.",
    visualRead: "Strong density and reflections, useful as a background or quick insert.",
    motionPrompt: "Slow centered push, cabinet screens flicker out of sync, character silhouette growing larger as the aisle narrows.",
    rightsNotes: arcadeRights,
  }),
  extraFrame({
    id: "ad-video-74-wes-visor-device-menu-closeup",
    imageNumber: 74,
    filename: "74-wes-visor-device-menu-closeup.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_42_24 PM.png",
    sha256: "fe84d906b51a29c34c73b09065b5fe030046fbf23abbd206f67766a736e0b724",
    assetCategory: "ui-badge",
    sceneFamily: "visor-courier",
    priority: "support",
    usage: "Device-menu reflection alternate for visor UI shots.",
    promptSummary: "White-haired visor courier closeup with device menu reflected on mirrored glasses.",
    alt: "A device menu reflects across a courier's mirrored visor.",
    visualRead: "Readable menu reflection; good B-side to image 40.",
    motionPrompt: "Menu selector moves one row in the visor reflection, blue light sweeps across the nose bridge, background stays soft.",
    rightsNotes: visorRights,
  }),
  extraFrame({
    id: "ad-video-75-psychic-creature-rooftop-sp-night",
    imageNumber: 75,
    filename: "75-psychic-creature-rooftop-sp-night.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_49_32 PM.png",
    sha256: "e56cba7c210d5d54bf8a99c1502f055c33d46610ac495e4d8ef2cac811e3a639",
    assetCategory: "hero-poster",
    sceneFamily: "rooftop-creature",
    priority: "primary",
    usage: "Night rooftop creature close shot with strongest blue mood.",
    promptSummary: "Pale psychic creature on dark rooftop with clamshell handheld device, city lights, and blue console-era branding.",
    alt: "A pale psychic creature stands on a dark rooftop holding a handheld device.",
    visualRead: "Strongest night creature mood frame with a clear handheld prop.",
    motionPrompt: "Night wind and rain, handheld glow illuminating the creature's hands, skyline bokeh blinking, tail silhouette moving slightly.",
    rightsNotes: creatureRights,
  }),
  extraFrame({
    id: "ad-video-76-shadow-vending-alley-profile",
    imageNumber: 76,
    filename: "76-shadow-vending-alley-profile.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_32_46 PM.png",
    sha256: "b7e65c48182eced499ea70a9b2e87356db04f245ee818ac0f65e8f45e90ad12c",
    assetCategory: "hero-poster",
    sceneFamily: "retail-exterior",
    priority: "support",
    usage: "Profile alley shot with vending light and noir street silhouette.",
    promptSummary: "Black-red antihero mascot in profile beside glowing vending machines on a dark rainy street.",
    alt: "A black-red mascot stands in profile beside bright vending machines.",
    visualRead: "Good profile silhouette for a quiet street cut.",
    motionPrompt: "Side profile hold, vending lights ripple across wet ground, character breath visible, distant signage flickering.",
    rightsNotes: shadowRights,
  }),
  extraFrame({
    id: "ad-video-77-psychic-creature-rooftop-sp-night-wide",
    imageNumber: 77,
    filename: "77-psychic-creature-rooftop-sp-night-wide.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_47_16 PM.png",
    sha256: "23c168a66bab9c843369b8c4b8eb86c6b0e5cd392da0118b8267902cd285ae87",
    assetCategory: "hero-poster",
    sceneFamily: "rooftop-creature",
    priority: "support",
    usage: "Wide rooftop creature silhouette with more skyline breathing room.",
    promptSummary: "Pale psychic creature standing on a rainy rooftop against a wide blue night skyline.",
    alt: "A pale psychic creature stands on a rooftop against a night skyline.",
    visualRead: "Best wide creature skyline frame for end-card negative space.",
    motionPrompt: "Slow skyline pan behind the creature, city lights shimmering in puddles, creature silhouette staying centered.",
    rightsNotes: creatureRights,
  }),
  extraFrame({
    id: "ad-video-78-wes-gamecube-billboard-fence",
    imageNumber: 78,
    filename: "78-wes-gamecube-billboard-fence.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_39_33 PM.png",
    sha256: "eb3421bbba1bdf80fade3aca8456a386dbfd06abe6c9d022e6e3a964d52ad776",
    assetCategory: "hero-poster",
    sceneFamily: "creature-companion-city",
    priority: "support",
    usage: "Fence-and-billboard courier shot for city billboard language.",
    promptSummary: "Blue-jacket visor courier at a chainlink fence with bright cube-console billboard and rainy night skyline.",
    alt: "A visor courier stands by a chainlink fence with a glowing billboard behind.",
    visualRead: "Useful billboard composition after replacing console marks with Action Replay signage.",
    motionPrompt: "Camera drifts along the fence, billboard glow pulsing, rain specks catching foreground light, courier turns toward camera.",
    rightsNotes: companionRights,
  }),
  extraFrame({
    id: "ad-video-79-wes-action-replay-visor-closeup-alt",
    imageNumber: 79,
    filename: "79-wes-action-replay-visor-closeup-alt.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_50_56 PM.png",
    sha256: "4ce92ca1d2fcc8bc3f54234a296b19b0cf9de1a42215cb137f5069f1099b9925",
    assetCategory: "ui-badge",
    sceneFamily: "visor-courier",
    priority: "alternate",
    usage: "Exact duplicate archive of image 38, kept for source provenance.",
    promptSummary: "Duplicate of the Action Replay visor courier closeup.",
    alt: "Duplicate closeup of a white-haired courier wearing a mirrored Action Replay visor.",
    visualRead: "Exact duplicate of image 38; use image 38 as the canonical version.",
    motionPrompt: "Use the motion direction from ad-video-38-wes-action-replay-visor-closeup if this duplicate is selected.",
    rightsNotes: "Same rights risk as image 38.",
    duplicateOf: "ad-video-38-wes-action-replay-visor-closeup",
  }),
  extraFrame({
    id: "ad-video-80-wes-action-replay-visor-coded-closeup",
    imageNumber: 80,
    filename: "80-wes-action-replay-visor-coded-closeup.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_53_57 PM.png",
    sha256: "7e018a2d55f922773498978dc7494b70171ed58c66cbdd8a0dbe349cf6343f85",
    assetCategory: "ui-badge",
    sceneFamily: "visor-courier",
    priority: "primary",
    usage: "Final visor-code closeup with strongest Action Replay reflection and hardware prop.",
    promptSummary: "White-haired visor courier closeup with Action Replay reflection and small memory-card-like hardware held near frame.",
    alt: "A visor courier holds a small memory-card-like device under an Action Replay visor reflection.",
    visualRead: "Best closing insert for the visor-courier batch because it includes both face and object.",
    motionPrompt: "Push from the handheld device to the visor reflection, logo flaring, code text crawling, cold blue highlight snapping into focus.",
    rightsNotes: visorRights,
  }),
  extraFrame({
    id: "ad-video-81-wes-gamecube-memory-card-closeup",
    imageNumber: 81,
    filename: "81-wes-gamecube-memory-card-closeup.png",
    originalPath: "/Users/zrelich/Desktop/ChatGPT Image May 10, 2026, 07_54_56 PM.png",
    sha256: "cfbd8c0bc666700d987fbc06be7c3f4b4cd2d1e14c238089ad6c03cdc20ceac2",
    assetCategory: "product-mockup",
    sceneFamily: "hardware-macro",
    priority: "primary",
    usage: "Handheld memory-card prop closeup for bridging courier, hardware, and final_mix archive motifs.",
    promptSummary: "White-haired visor courier holds a dark cube-console memory-card-like object toward camera under blue Action Replay visor light.",
    alt: "A visor courier holds a dark memory-card-like device close to the camera.",
    visualRead: "Best object handoff frame in the expanded batch.",
    motionPrompt: "Macro rack focus from the memory-card prop to the visor, blue reflection flaring, fingers steadying the object, background falling into black.",
    rightsNotes: "Contains Pokemon Colosseum/Wes/GameCube/Nintendo-style references and memory-card prop marks. Replace with original Action Replay hardware.",
  }),
];
